name: Checks 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

    - name: Check formatting
      run: go fmt ./...

    - name: Run linter
      run: go install golang.org/x/lint/golint@latest && golint ./...

    - name: Run static analysis
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

    - name: Check spelling
      run: go install github.com/client9/misspell/cmd/misspell@latest && misspell -error .

    - name: Build
      run: go build ./...
